[package]
name = "orzir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orzir-macros = { path = "../orzir-macros" }
orzir-core = { path = "../orzir-core" }

arpfloat = "0.1.10"
thiserror = "1.0.58"